#################################
#             Backend           #
#################################
backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;
use-damage = false;
vsync = true;
corner-radius = 12;
#################################
#            Blur               #
#################################
blur: {
  method = "dual_kawase";
  strength = 3;
  background = true;
  background-frame = true;
  background-fixed = true;
}

# Исключаем Plank из размытия, чтобы убрать полосу на весь низ	
blur-background-exclude = [
  "window_type = 'desktop'",
  "class_g = 'xfce4-screenshooter'",
  "class_g = 'Xfce4-screenshooter'",
    "class_g = 'Conky'",
  "class_g = 'conky'",
  "window_type = 'dock' && class_g = 'Plank'",
  "_GTK_FRAME_EXTENTS@:c"
];
# Применяем радиус только к конкретному классу окна
corner-radius = 12;

rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'Plank'",
    "class_g = 'Conky'",
  "class_g = 'conky'",
  "class_g = 'plank'",
  "class_g = 'Xfce4-panel'",
  "x = 0 && y = 26" 
];
# Чтобы скругление применялось только к Conky (если не хотите скруглять все окна)
#################################
#           Opacity             #
#################################
# Здесь мы задаем прозрачность для нужных окон
opacity-rule = [
  "90:class_g = 'Xfce4-panel'",
  "90:class_g = 'Xfce4-popup-whiskermenu'",
  "96:class_g = 'Thunar'",
  "95:class_g = 'thunar'",
  # Plank будет просто прозрачным, но без размытия фона под ним
  "100:class_g = 'Plank'"
];

#################################
#           Fading              #
#################################
fading = true;
fade-in-step = 0.08;
fade-out-step = 0.08;
fade-delta = 4;

#################################
#           Shadows             #
#################################
shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.4;

shadow-exclude = [
  "class_g = 'Plank'",
  "_GTK_FRAME_EXTENTS@:c",
    "class_g = 'Conky'",
  "class_g = 'conky'",
  "class_g = 'Xfce4-panel'"
];

#################################
#           Wintypes            #
#################################
wintypes:
{
  menu          = { shadow = false; full-shadow = false; blur-background = true; };
  dropdown_menu = { shadow = false; full-shadow = false; blur-background = true; };
  popup_menu    = { shadow = false; full-shadow = false; blur-background = true; };
  utility       = { shadow = false; full-shadow = false; blur-background = true; };
};

textrules: (
  {
    match = "maximized || fullscreen";
    corner-radius = 0;
  }
)
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
focus-exclude = [
    "class_g = 'Xfwm4'",
    "name = 'Desktop'"
];
